application: glass-notify
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static
  http_headers:
    Cache-Control: max-age=31556926

- url: .*
  script: main.application